### ISSUE TITLE
ruby 2.3.1 buildpack download failed

### ISSUE THREAD

**Issue by DanielRedOak** [crohr/pkgr#102]
Similar to #78 , any chance we could get 2.3.1 support?
heroku-buildpack-ruby/lib/language_pack/shell_helpers.rb:56:in `run!': Command: 'set -o pipefail; curl -v -L --fail --retry 10 --retry-delay 1 --connect-timeout 60 --max-time 300 https://s3-external-1.amazonaws.com/pkgr-buildpack-ruby/current/ubuntu-14.04/ruby-2.3.1.tgz -s -o - | tar zxf - ' failed unexpectedly: (StandardError)

**Comment by crohr** [comment]
Yes I need to release a new version of pkgr with the updated buildpack, but you can already specify `--buildpack https://github.com/pkgr/heroku-buildpack-ruby#buildcurl` to get ruby 2.3.1

**Comment by DanielRedOak** [comment]
We've actually been using the heroku buildpacks directly in the meantime without issue but thanks for this bit of info!

**Comment by crohr** [comment]
If you're packaging only for ubuntu 14.04 then yes the official buildpack works. But for other distributions you would need to use the pkgr version.

**Comment by DanielRedOak** [comment]
Yep, I looked through things to make sure. It might be useful to have the #buildcurl bit and the difference between heroku buildpacks vs pkgr maintained ones in the docs, but it's not critical.  Thanks!

**Comment by crohr** [comment]
v1.5.1 now includes the correct buildpack URLs so that you can automatically get the latest ruby versions for your platform if you want.
