### ISSUE TITLE
Please release master

### ISSUE THREAD

**Issue by rylarson** [crohr/pkgr#106]
If we could get a new release from master, I could really use the `default_dependencies: false` feature that is part of master but not part of `v1.44`

Thanks

**Comment by crohr** [comment]
v1.5.0 was just released, sorry for the wait! [CHANGELOG](https://github.com/crohr/pkgr/blob/master/CHANGELOG.md#150---20160908)

**Comment by crohr** [comment]
Just released 1.5.1 to add the proper Ruby buildpack location + Python support.

**Comment by jacob-carlborg** [comment]
How unfortunate it was done right now: https://github.com/crohr/pkgr/pull/105#commitcomment-18954283.
