### ISSUE TITLE
gem install pkgr no longer works

### ISSUE THREAD

**Issue by qur2** [crohr/pkgr#113]
The installation with ruby 1.9 fails because it tries to install mustache 1, which requires ruby2.

``` bash
osboxes@osboxes:~/src$ sudo gem install pkgr
Fetching: pkgr-1.5.1.gem (100%)
Fetching: clamp-1.0.1.gem (100%)
Fetching: archive-tar-minitar-0.5.2.gem (100%)
Fetching: io-like-0.3.0.gem (100%)
Fetching: ruby-xz-0.2.3.gem (100%)
Fetching: stud-0.0.22.gem (100%)
Fetching: mustache-1.0.3.gem (100%)
ERROR:  Error installing pkgr:
    mustache requires Ruby version ~> 2.0.
```

I checked the dependencies and couldn't find which one actually lists mustache >= 1.

Any help/thoughts?

**Comment by jacob-carlborg** [comment]
That's weird. I cloned Pkgr locally, run `bundle`. This is the dependencies I get:

```
$ bundle list
Gems included by the bundle:
  * CFPropertyList (2.2.8)
  * arr-pm (0.0.10)
  * backports (3.6.8)
  * bundler (1.9.7)
  * cabin (0.8.1)
  * childprocess (0.5.9)
  * clamp (0.6.5)
  * diff-lcs (1.2.5)
  * facter (2.4.6)
  * ffi (1.9.10)
  * fpm (1.4.0)
  * json (1.8.3)
  * mixlib-log (1.7.1)
  * mixlib-shellout (1.6.1)
  * pkgr (1.5.1)
  * rake (10.5.0)
  * rspec (2.99.0)
  * rspec-core (2.99.2)
  * rspec-expectations (2.99.2)
  * rspec-mocks (2.99.4)
  * thor (0.19.1)
```

**Comment by qur2** [comment]
Hey, thanks for your interest. I think several of those dependencies have mustache as their own.

In the meantime, I fixed my issue by using `ruby2.0` and `gem2.0`.

**Comment by jacob-carlborg** [comment]
`bundle list` lists all dependencies, both direct and indirect.

**Comment by qur2** [comment]
Some of them have `mustache` as a dev dependency (e.g. `bundler`: https://rubygems.org/gems/bundler). Maybe I was doing something wrong and installed packages in dev mode? How would I prevent that from happening?

**Comment by jacob-carlborg** [comment]
I noticed that on Linux it installs the dev dependencies but not on macOS. Maybe pkgr should include the Gemfile.lock, not sure if it makes a difference.

**Comment by crohr** [comment]
Including the Gemfile.lock is generally not recommended for gems. I think I need to officially end support for ruby 1.9. What do you think?

**Comment by jacob-carlborg** [comment]
> Including the Gemfile.lock is generally not recommended for gems

As far as I understand, the lock file should be included for applications but not for libraries. But if you expect someone to add pkgr as a dependency in their Gemfile, perhaps best to not include it.

> I think I need to officially end support for ruby 1.9. What do you think?

Yes, as long as it can still package applications that need Ruby 1.9.

**Comment by crohr** [comment]
@jacob-carlborg yes the ruby version with which you run `pkgr` doesn't impact which ruby version your packages can use.

**Comment by jacob-carlborg** [comment]
Yes, then please drop the support for 1.9.
