### ISSUE TITLE
Update dependency for rake

### ISSUE THREAD

**Issue by obfuscoder** [crohr/pkgr#119]
The dependency for rake is locked to version 10.x. Last 10.x version has been released more than a year ago. Current version of Rake is 12.x which was released last year.

**Comment by obfuscoder** [comment]
One year has passed, yet the dependency to rake is still locked on 10.x. Is this project still maintained?

**Comment by obfuscoder** [comment]
I can see that the rake dependency is set to 10.x because rake dropped support for Ruby version 1.8.7 in Rake 11.0.0 and again dropped Ruby 1.9.3 support in rake version 12.3.0. I ask myself whether it is really necesary to declare the rake version. Sure enough if you want to have Ruby 1.8.7 support during pkgr development, it should be ok to define it as development dependency.

**Comment by obfuscoder** [comment]
I created PR #140 which seems to build nicely. I updated the minimum required Ruby version to 1.9.3, but I can revert this if necessary.

**Comment by crohr** [comment]
PR was merged, thanks! Closing.
