### ISSUE TITLE
Pkgr doesn't create the cron directory if it doesn't exist

### ISSUE THREAD

**Issue by jacob-carlborg** [crohr/pkgr#121]

**Comment by crohr** [comment]
Yes, actually it should add a dependency on the cron system package in case it is not installed yet (I believe that's the issue you ran into)

**Comment by jacob-carlborg** [comment]
Do you mean that Pkgr itself should add the dependency or that I would need to do that?

**Comment by crohr** [comment]
For now you need to do it yourself by adding to the `dependencies` of your project (e.g. `cron` for ubuntu). But we could add it by default to the default dependencies in case a cron is specified in the `.pkgr.yml` file (https://github.com/crohr/pkgr/tree/master/data/dependencies)

**Comment by crohr** [comment]
Just need to check the name of the package on all distros

**Comment by jacob-carlborg** [comment]
> For now you need to do it yourself

Just checking, because we came to that conclusion a couple of months ago here: https://github.com/crohr/pkgr/pull/122.
