### ISSUE TITLE
pkgr fails to create sysv start files for 'service'

### ISSUE THREAD

**Issue by wkoszek** [crohr/pkgr#124]
Hi. Thanks for `pkgr`. 

I have an empty Rails app. I'm attempting to package it and install it in the VM for testing purposes. After installing everything seems fine, however the 'service' doesn't have the `wordmogul` script. So I can't do: `service wordmogul start` which would be very nice.

My full steps:

```
git clone https://github.com/wkoszek/wordmogul
cd wordmogul
vagrant up dev
vagrant ssh dev
cd /vagrant
make pkg
dpkg -i wordmogul*.deb
apt-get install -f
```

`make pkg` builds the `.deb` with this script: 

https://github.com/wkoszek/wordmogul/blob/master/deploy/package.sh

I tried: passing `-runner sysv`, `-runner systemd`, `-runner upstart`. It didn't help. After installing or unpacking, there aren't any startup scripts generated in `/etc`. I'd expect something to show up in `/etc/init`.

Here's a snippet with `--debug` of my `package.sh` script:

[pkgr_wordmogul.txt](https://github.com/crohr/pkgr/files/930210/pkgr_wordmogul.txt)

Passing `--force-os=ubuntu-14.04` didn't seem to help. I tried it with `-runner` too.

**Comment by crohr** [comment]
Have you tried running the `scale` command after you installed your package?

**Comment by wkoszek** [comment]
@crohr I'm trying from a different Mac now, not my home laptop. I recreated the development VM and it seems like it's running fine here:

```
root@vagrant-ubuntu-trusty-64:/vagrant# wordmogul scale web=1
Scaling up...
wordmogul-web-1 start/running, process 12566
wordmogul-web start/running
wordmogul start/running
--> done.
```

And I do have `service wordmogul` working fine here:

```
/etc/init.d/wordmogul
/etc/logrotate.d/wordmogul
/etc/default/wordmogul
/etc/apt/sources.list.d/wordmogul.list
/etc/init/wordmogul.conf
/etc/init/wordmogul-web-1.conf
/etc/init/wordmogul-web.conf
/etc/wordmogul
/etc/wordmogul/conf.d
/etc/wordmogul/conf.d/other
```

Maybe I have an outdated Vagrant box for `ubuntu/trusty64` at home. Will try it tonight again and report the findings.

**Comment by wkoszek** [comment]
@crohr On a newer Vagrant `ubuntu/trusty64` from `20170405.0.0` the 'service wordmogul start' doesn't work right after the installation. I think this one I have at home.

```
vagrant box update
==> dev: Checking for updates to 'ubuntu/trusty64'
    dev: Latest installed version: 20170405.0.0
    dev: Version constraints:
    dev: Provider: virtualbox
==> dev: Box 'ubuntu/trusty64' (v20170405.0.0) is running the latest version.
```

This is the log:

[pkgr_from_vagrant_ubuntu_trusty64_20170405.0.0.txt](https://github.com/crohr/pkgr/files/930642/pkgr_from_vagrant_ubuntu_trusty64_20170405.0.0.txt)

But looks like yours:

```
wordmogul scale web=1
```

Makes the files in `/etc/init/...` show up. Didn't expect that... Is this how it's supposed to work?

**Comment by wkoszek** [comment]
@crohr did stuff I pasted here make any sense? Just wondering if that's the expected behavior. And if yes, I'd close this bug and maybe make a doc. pull request about this.

**Comment by crohr** [comment]
Yes the init scripts are only installed when you run the `scale` command (you can put it in a postinstall file if you want it to run automatically, although it is not enabled by default since you generally don't want services starting right after package installation, and you might also need to set environment variables first, etc.).

Happy to merge a PR if this wasn't clear enough from the README.

**Comment by crohr** [comment]
There is actually a note in the README already. Closing.
