### ISSUE TITLE
Add option to define the port or socket where the service listens

### ISSUE THREAD

**Issue by monotek** [crohr/pkgr#126]
I use a nginx proxy to make my ruby app available via https. 
Unfortunately port 3000  is still accessible without https because it listens on 0.0.0.0.
Therefore it would be nice one could configure the package to listen to a specified IP like 127.0.0.1 or to a socket.

**Comment by lukaszkorecki** [comment]
That sounds like your application's config not a requirement of your packaging system, right?

You can do this in your procfile:

```
web: ./start-server -b $BIND_ADDR -p $PORT
```

and use env vars to instruct your app to use designated IP/Port/etc

**Comment by monotek** [comment]
Ok, thanks.
Have to try if env vars will be also used when init scripts are created from packager.io service

**Comment by crohr** [comment]
@lukaszkorecki is right, you need to parametrize your `web` command so that it can read from the `PORT` env variable that is automatically set by `pkgr` (it works exactly the same whether you manually package with `pkgr` or use packager.io).

For rails that would mean something like:
```
# Procfile
web: bundle exec rails -b ${BIND:=127.0.0.1} -p ${PORT:=3000}
```

**Comment by monotek** [comment]
Thanks! It worked :-)
