### ISSUE TITLE
Add Debian 9 support

### ISSUE THREAD

**Issue by monotek** [crohr/pkgr#128]
Debian 9 is out and should be supported.

**Comment by monotek** [comment]
Added pull request: https://github.com/crohr/pkgr/pull/129

**Comment by crohr** [comment]
@monotek debian-9 is deployed on Packager.io. Let me know if you'd like to test it on your non-official Zammad repo, in which case I'll bump the required pkgr version for that repo. I'll run a few more tests on my side (since it also includes the changes on the `master` branch) before making it available for everyone.

**Comment by monotek** [comment]
We can test it in zammads devel repo @ https://packager.io/gh/zammad/zammad/refs/develop

**Comment by crohr** [comment]
@monotek as it is, if I update for the main repo, it will update for all refs, so unless you don't plan on releasing a new stable version soon it might not be a good idea.

**Comment by monotek** [comment]
We can also use this repo i use for testing:
https://packager.io/gh/monotek/zammad
So nobody would be affected by any changes.

**Comment by crohr** [comment]
@monotek sorry for the delay, I just enabled version 1f2437d7871abef884a7435aec06b336d97b8986 for monotek/zammad. Let me know how it goes.

**Comment by monotek** [comment]
Triggered a build which should test it: https://packager.io/gh/monotek/zammad/builds/411

**Comment by monotek** [comment]
@crohr 
Any update on this?

**Comment by monotek** [comment]
@crohr 

It works in my personal repo @ https://packager.io/gh/monotek/zammad/builds/440/install/debian-9
But not in our official repo @ https://packager.io/gh/zammad/zammad/builds/2481/logs/debian-9

Is there a schedule when Debian 9 will be globally activated?

**Comment by martini** [comment]
++

**Comment by rolfschmidt** [comment]
++

**Comment by crohr** [comment]
@monotek Updated to latest version (`724fa0afa26c5f039a6433c78505ae0c6ed4ee0f`) on both your personal and official repo. This will be globally enabled on packager.io by the end of the month. I'm very sorry for the delay in handling this, but thanks again for testing it out.

**Comment by crohr** [comment]
@martini & @rolfschmidt let me know your repo names via support@packager.io and I can also enable it for you

**Comment by monotek** [comment]
@crohr 

Thanks a lot! :-)

Debian 9 package was successfully build: https://packager.io/gh/zammad/zammad/builds/2510/logs/debian-9

**Comment by audhen** [comment]
Aaaand it's broken again.
