### ISSUE TITLE
Cannot build package for/on raspberrypi  armv7l 

### ISSUE THREAD

**Issue by mavu** [crohr/pkgr#131]
Hi, 

My rails app needs to run on an raspberryPI (armv7l) and this is the result:

-----> Fetching buildpack https://github.com/pkgr/heroku-buildpack-ruby.git at buildcurl
-----> Ruby app
[2017-08-03T11:56:21+00:00] WARN: Can't create "/opt/testapp", which may be needed by some buildpacks.
-----> Compiling Ruby/Rails
-----> Using Ruby version: ruby-2.4.1
bash: vendor/ruby-2.4.1/bin/ruby: cannot execute binary file: Exec format error
 !
 !     Problem detecting bundler vendor directory:
 !   
     ! ERROR: compile failed

**Comment by crohr** [comment]
Hello, Raspberry builds are not supported at the moment. This would require precompiled builds of the ruby versions for the target architecture.
