### ISSUE TITLE
/usr/bin conflicts with the "filesystem" package on CentOS 7

### ISSUE THREAD

**Issue by jacob-carlborg** [crohr/pkgr#133]
On CentOS 7, when building the package with the `--disable-cli` flag, the following error occurs when trying to install the built package:

```
Transaction check error:
  file /usr/bin from install of <package>.x86_64 conflicts with file from package filesystem-3.2-21.el7.x86_64
```

**Comment by BladeTail** [comment]
If you're trying to use `rpm -ivh xxx.rpm` to install a package in the centOS7, you can try to add `--force` attribute which should be `rpm -ivh --force xxx.rpm`.

**Comment by jacob-carlborg** [comment]
I'm using a fork with my fix, the one linked above.
