### ISSUE TITLE
Ruby version

### ISSUE THREAD

**Issue by KernelPanicAUS** [crohr/pkgr#135]
Hello there, I'm trying to package a rails application and was surprised to find `pkgr` using a ruby that I can't seem to find on my system.

```
-----> Compiling Ruby/Rails
-----> Using Ruby version: ruby-2.2.4
```

```
ubuntu@build-host:/opt  $ ruby -v
ruby 2.3.4p301 (2017-03-30 revision 58214) [x86_64-linux]
```

Does `pkgr` ship with its own built-in ruby?

**Comment by monotek** [comment]
You can define the used ruby version in .ruby-version.yml file.

**Comment by andyjeffries** [comment]
We get an error when trying to use a newer version than Ruby 2.3.0. It appears we get a permission denied from AWS S3 when trying to download the source to compile it.

https://gist.github.com/NDuggan/95704b77c059d29ea1dd12d84755c63e

**Comment by leshiynyc** [comment]
@monotek  Can you please elaborate ? I've been trying to find anything on .ruby-version.yml in the docs without any luck. 
We're experiencing the same problem as KernelPanicAUS. 
I created .ruby-version.yml with the following content:
---
ruby-1.9.3-p484

That doesn't seem to work. 
Running the build with in rvm with  the above version installed.

# which pkgr
/usr/local/rvm/gems/ruby-1.9.3-p484/bin/pkgr
# which ruby
/usr/local/rvm/rubies/ruby-1.9.3-p484/bin/ruby

**Comment by nodanaonlyzuul** [comment]
Hi, I work with @leshiynyc.

To add on to @leshiynyc's comment....We've tried this with `.ruby-version` too...which I _thinnnnkkk_ may be what you meant, not `.ruby-version.yml`.

[.ruby-version is the rvm way of switching environments](https://rvm.io/workflow/projects#project-file-ruby-version).

Let us know if there are any environment details we can provide to help.
Thanks for your time.

**Comment by nodanaonlyzuul** [comment]
For posterity - we've seen that although the current version of rvm isn't being respected (as @KernelPanicAUS reports), setting the ruby version in the Gemfile works to change the ruby version.

Snippet https://packager.io/documentation/ruby/#mri-ruby-versions:

> All MRI Ruby versions 1.9+ and 2.+ are supported. Newer versions are
automatically compiled on-demand if you ask for them. Your version will either default to 2.3.4, or the version you've specified in your Gemfile. For instance:

```bash
cat Gemfile
source "https://rubygems.org"

ruby "2.3.0"

# rest of your Gemfile
```

...end snippet

**Comment by KernelPanicAUS** [comment]
Can confirm @nodanaonlyzuul 's solution does work.
Closing ticket...
