### ISSUE TITLE
Support for mongodb service during build

### ISSUE THREAD

**Issue by rbclark** [crohr/pkgr#136]
Hello, I'm attempting to use pkgr to package an application which requires mongo during the assets:precompile stage. I was initially intrigued by the `services:` option however I see it only currently supports postgresql and redis. I tried adding a build_dependency for mongodb however build_dependencies seem to run after services are started, making it essentially useless for this purpose. 

To add another step of confusion, the version of mongodb which comes with most OS's is very out of date. The one that comes in the Ubuntu 16.04 repositories (mongodb-server) for example is v2.6.10. In my case this doesn't seem to be a problem since I have tested and the application I am attempting to compile can handle is built for mongo 3.4 but does not seem to mind if asset precompilation is done on 2.6.

Do you have any suggestions on the best way to go about handling adding this service?

**Comment by rbclark** [comment]
I have worked around it for now by using the following:

    build_dependencies:
      - mongodb-server
    dependencies:
      - mongodb-org-server (= 3.4.5)
    before:
      - mkdir -p /tmp/db
      - /usr/bin/mongod --dbpath /tmp/db --fork --syslog
    targets:
      ubuntu-16.04:

It is not the cleanest thing however it gets the build completed. Support for mongodb in the services block would still definitely be appreciated.

**Comment by crohr** [comment]
mongodb won't be supported for the time being.
