### ISSUE TITLE
Handling of "release" builds

### ISSUE THREAD

**Issue by rbclark** [crohr/pkgr#137]
First off, I apologize if this is not the correct place to file this issue since it is an issue with the hosted version of pkgr, not so much pkgr itself. Every push to master is not necessarily a release for our project. Instead all of our official releases are tagged accordingly. Does pkgr have any support for only building tagged releases of our software instead of every push to master? When using Docker we normally get around this by having a latest and a release-latest tag. Having a stable and unstable channel or anything of the sort  on the hosted service would most likely solve this issue.

**Comment by crohr** [comment]
@rbclark you could get around this by creating a branch dedicated to your releases (e.g. you could have `master`, `stable`, `testing`, etc.). Would that work for you?

**Comment by rbclark** [comment]
That is what I have ended up going with for now. I do feel as if tagging is a more common release pattern however I have no problem with this method if it is the one you wish to support. Thanks!
