### ISSUE TITLE
Support for multiline Procfile entries

### ISSUE THREAD

**Issue by kostadin-damyanov-prime** [crohr/pkgr#152]
It would be nice if a long **Procfile** command line could be split in multiple lines.
For example:
```
web: web-executable \
    --config=/path/to/config \
    --option=value
worker: worker-executable
```

Another example:
https://smartmob-rfc.readthedocs.io/en/latest/1-procfile.html#multiline-commands

**Comment by crohr** [comment]
@kostadin-damyanov-prime currently the best way to do this is to put your command in a script, and reference this script from your Procfile.
