### ISSUE TITLE
You must use Bundler 2 or greater with this lockfile

### ISSUE THREAD

**Issue by rbclark** [crohr/pkgr#153]
Just encountered this issue when trying to build a ruby package with a Gemfile.lock containing

```
BUNDLED WITH
   2.0.1
```

Is there anything I can do to use bundler 2 with packager?

**Comment by crohr** [comment]
Bundler2 is supported in https://github.com/crohr/pkgr/commit/6c7985df85468022480ffec225ae06c5d2cac8f3. It is now available on packager.io, let me know if it works for you.

**Comment by rbclark** [comment]
Yep I just ran a build with it and it worked, thanks!
