### ISSUE TITLE
Can't find gem bundler (>= 0.a) with executable bundle

### ISSUE THREAD

**Issue by Bialogs** [crohr/pkgr#162]
I am getting the following error when trying to package a Ruby 2.6.3 / Rails 5 application using bundler 2.0.2.
```
 !     There was an error parsing your Gemfile, we cannot continue
 !     /tmp/tmp.p0QZiS8i4W/lib/ruby/2.5.0/rubygems.rb:289:in `find_spec_for_exe': can't find gem bundler (>= 0.a) with executable bundle (Gem::GemNotFoundException)
 !     from /tmp/tmp.p0QZiS8i4W/lib/ruby/2.5.0/rubygems.rb:263:in `bin_path'
 !     from /tmp/d20190814-31084-54piqu/bundler-2.0.1/bin/bundle:22:in `<main>'
```
One related post about this from bundler: https://bundler.io/blog/2019/01/04/an-update-on-the-bundler-2-release.html

However, the output of `/tmp/d20190814-31084-54piqu/bundler-2.0.1/bin/bundle --version` is actually 2.0.2, so it seems like I would not hit that issue. It is a bit suspect that it is installed in a 2.0.1 directory.

-- Edit --
So I reverted the gemfile to 1.17.3  and there are several mismatches:
`Installing dependencies using bundler 1.15.2`  but then
`Warning: the running version of Bundler (1.17.2) is older than the version that created the lockfile (1.17.3)`

It is also worth noting I'm building the `pkgr` gem from master branch on GitHub for these tests.

**Comment by crohr** [comment]
Newer ruby buildpacks with newer bundler version probably have fixed this issue. Please reopen if needed.
