### ISSUE TITLE
Drop support for Ruby 1.9.x

### ISSUE THREAD

**Issue by obfuscoder** [crohr/pkgr#163]
Currently pkgr requires ruby 1.9.x. It cannot be used with Ruby 2.x as pkgr does have a runtime dependency to rake 12.2.x. Rake 12.3.x+ requires ruby version 2.x.

The problem arises when a project is using pkgr to build the debian package and is having a dependency to rake 12.3+.

I suggest having a new pkgr major version with dropping support for ruby 1.x so we can require ruby 2.x and remove the dependency limit for rake.

**Comment by crohr** [comment]
I believe this is fixed?
