### ISSUE TITLE
CentOS 8 build is failing (missing build pack)

### ISSUE THREAD

**Issue by thorsteneckel** [crohr/pkgr#164]
Hey @crohr - I just saw [your tweet](https://twitter.com/crohr/status/1201903369608151040) and was eager to add the Zammad CentOS 8 package. Unfortunately the build is failing. See: https://packager.io/gh/zammad/zammad/builds/4213/logs/centos-8

Could you please have a look? Thanks a ton.

Bests,
  Thorsten

**Comment by crohr** [comment]
Yes the Packager.io config is a bit behind. I’ll update it ASAP.

**Comment by crohr** [comment]
It should be fixed now

**Comment by thorsteneckel** [comment]
Retry failed: https://packager.io/gh/zammad/zammad/builds/4213/logs/centos-8
Do I need to trigger another fresh build?

**Comment by crohr** [comment]
Ok this time the build is starting fine. Your repo was pinned to a specific pkgr version.

**Comment by thorsteneckel** [comment]
Thanks @crohr <3
