### ISSUE TITLE
Ubuntu 20.04

### ISSUE THREAD

**Issue by ankane** [crohr/pkgr#166]
Hey @crohr, thanks for creating this and running packager.io all these years!

The latest Ubuntu LTS was released last week - would be great to see pkgr support it.

Also, it appears the `doc` subdomain has an expired SSL certificate: https://doc.packager.io/documentation

**Comment by crohr** [comment]
Hi @ankane, thanks for the ping. Ubuntu 20.04 support is coming, and I'll fix the documentation certificate ASAP!

**Comment by crohr** [comment]
@ankane ubuntu 20.04 support has landed in `master`, and is now available on Packager.io (just use the `ubuntu-20.04` target).

**Comment by ankane** [comment]
You're awesome, thanks @crohr!
