### ISSUE TITLE
Sles15-Support

### ISSUE THREAD

**Issue by MrGeneration** [crohr/pkgr#167]
Heya,

would it be possible to have SLES 15 support in the future?
I've tried on my own earlier, but failed miserably because of so many dependencies. ^^"

Looking forward to your feedback. 🚀

**Comment by christophvw** [comment]
any news on this? We really need Zammad packages for SLES 15!

**Comment by crohr** [comment]
SLES-15 beta support has landed. Use `sles-15` as the target name.
