### ISSUE TITLE
Debian 11 Bullseye

### ISSUE THREAD

**Issue by KrisLowet** [crohr/pkgr#170]
Hello

Would it be possible to add support for Debian 11 Bullseye?

Thank you

**Comment by crohr** [comment]
Yes, there is a PR for it https://github.com/crohr/pkgr/pull/171. Need to test a few things further but looking good.

**Comment by KrisLowet** [comment]
Hi crohr, how are the tests going?

**Comment by crohr** [comment]
@KrisLowet this works, I've merged into the main branch

**Comment by KrisLowet** [comment]
Great, thanks!
