### ISSUE TITLE
Packager allows URL manipulation

### ISSUE THREAD

**Issue by MrGeneration** [crohr/pkgr#172]
Even if a package is not part of the build process, as long as packager at least partly, knows the distribution and it's release version, you can do this:

https://dl.packager.io/srv/zammad/zammad/stable/installer/debian/11.repo

According to a user this also somewhat works (but shouldn't).

**Comment by crohr** [comment]
@MrGeneration what is the issue here? Yes the underlying storage can provide dynamically generated repository URLs, but there won't be any packages in there. Or am I not understanding your point?

**Comment by MrGeneration** [comment]
The issue on this behavior is that a user assumes that the distribution is already supported.
Then adds it to the system and tries to install it.

Then those clever people land on my door and complain that installation of things is not possible "no install candidate".
In my opinion it's bad user experience. If something does not exist, it should not be available.

You can actually see the result of this behaviour here:
https://github.com/zammad/zammad-documentation/pull/200#issuecomment-934318190

But that's my opinion.

**Comment by crohr** [comment]
I'm going to close this for now
