### ISSUE TITLE
Problem syncing Zammad repo via Red Hat Satellite / Pulp3

### ISSUE THREAD

**Issue by SchnabeJ** [crohr/pkgr#177]
We try syncing the Zammad repository to our Red Hat Satellite server which fails due to pulp 3's meta data check. I reached out ot the Zammad community and was forwarded with the issue to pkgr. Is there a way to fix the meta data so that the respective repository works with pulp3? Thanks in advance for your help!

**Infos:**

- Used Zammad version: 5.X
- Used Zammad installation type: (source, package, docker-compose, …) rpm via yum/dnf from on-premise Red Hat Satellite server
- Operating system: rhel 8

**Expected behavior:**

- The Zammad Enterprise Linux repository (https://dl.packager.io/srv/rpm/zammad/zammad/stable/el/8/x86_64) should be mirrored/synced to our on-premise Red Hat Satellite server via Pulp 3 following a schedule.

**Actual behavior:**

- Pulp 3 is not able to sync the repo due to a problem with the metadata.
- “Package id from primary metadata does not match package id from filelists, other metadata”
- The Red Hat support looked into the issue together with Pulp developers and found that pulp3 is trying to match the first pkgid from primary.xml.gz with the first pkgid from filelists.xml.gz which will always fail so that this error makes sense.

**Steps to reproduce the behavior:**

- Try syncing the Zammad repository via Red Hat Satellite / Pulp3

**Comment by crohr** [comment]
@SchnabeJ thanks for the report. I am aware of that issue and have a possible fix ready. Just need a bit of time to test and release it properly. I'll keep you updated.

**Comment by SchnabeJ** [comment]
@crohr Thank you very much for your fast reply and great to hear that there might be a solution! Also thanks for keeping me posted.

**Comment by crohr** [comment]
@SchnabeJ this should now be fixed. Could you let me know either way?

**Comment by SchnabeJ** [comment]
@crohr Great! This appears to have worked! Thank you very much for your work,
