### ISSUE TITLE
Please improve download speed of openproject in China, only  50kB/s

### ISSUE THREAD

**Issue by Huaweidev** [crohr/pkgr#179]
Please improve download speed of openproject in China, only  50kB/s, almost spend me 1 hours:
`Get:59 https://dl.packager.io/srv/deb/opf/openproject/stable/12/debian 11/main amd64 openproject amd64 12.5.6-1685597719.35aacb9b.bullseye [213 MB]                                                     50kB/s`

I try to use a Microsoft Azure VPN tunnel to speed up but no use. Is there any way to speed up?

**Comment by crohr** [comment]
Answered in a separate ticket. I can't do anything here.
