### ISSUE TITLE
Support for EL9

### ISSUE THREAD

**Issue by ombre8** [crohr/pkgr#182]
Hi

we would really like to install Zammad on a EL 9 Server, since [they support all the Distributions packager.io supports](https://community.zammad.org/t/what-about-rocky-linux-support/11147/5) it would be very nice if you could also support EL9. Apparently there are already some things in place, but packaging fails because there is a `curl-minimal` installed which conflicts with `curl`: https://packager.io/gh/ombre8/zammad/builds/5/logs/centos-9

As I can't find `curl` as a (build)-dependency in Zammad, I assume this is something that is built in pkgr?

I'm happy to help, but I somehow can't figure out where to start debugging ;) Any help is appreciated. Thanks

**Comment by ombre8** [comment]
@crohr any hint at all?

**Comment by crohr** [comment]
@ombre8 I'll have a look, but `curl-minimal` is not part of the default build dependencies so it must come from somewhere else.

**Comment by ombre8** [comment]
hi @crohr it's the other way around, the EL9 image has `curl-minimal` pre-installed, and `curl` seems to be a build dependency, but installing `curl` fails since it conflicts with the pre-installed `curl-minimal`

**Comment by crohr** [comment]
@ombre8 I've force-installed `curl` in the base image with `--allowerasing` option. Could you retry and see if it works now?

**Comment by ombre8** [comment]
Nice thanks, now it fails with a missing build pack: https://packager.io/gh/ombre8/zammad/builds/11/logs/centos-9

**Comment by crohr** [comment]
Closing, as this has been working since quite a while now.
