### ISSUE TITLE
Support for Ubuntu 24.04

### ISSUE THREAD

**Issue by StormTrooper** [crohr/pkgr#184]
Can you add support for Ubuntu 24.04 LTS?

**Comment by crohr** [comment]
@StormTrooper hello, yes it should come before end of month!

**Comment by crohr** [comment]
Support has landed. Do you want to beta-test it on packager.io? If so you can give me your repo name.

**Comment by StormTrooper** [comment]
Excellent. 
https://packager.io/gh/StormTrooper/InvenTree

**Comment by crohr** [comment]
@StormTrooper ok, you can now use `ubuntu-24.04` in your `.pkgr.yml` file!
