### ISSUE TITLE
Custom upstart script

### ISSUE THREAD

**Issue by fatum** [crohr/pkgr#25]
Hi! i have one question..

Can i add custom upstart script, for example i need restart my unicorn workers with zero downtime?

**Comment by bezreyhan** [comment]
Hello, we need to source our environment variables from the upstart script. Is there a way to designate our own script?

**Comment by DanielRedOak** [comment]
+1 on the need for a custom script or ability to send signals to processes.  Ie USR2 to something like Puma or Unicorn
