### ISSUE TITLE
Unable to download Ruby buildpack

### ISSUE THREAD

**Issue by aidansteele** [crohr/pkgr#31]
I get the following error when trying to build a package. I'll also note that another repo still builds fine, maybe because the buildpack is cached? 

```
$ time pkgr package --verbose webservices-rb
-----> Ruby app
-----> Compiling Ruby/Rack
 !
 !     Command: 'set -o pipefail; curl --fail --retry 3 --retry-delay 1 --connect-timeout 3 --max-time 30 https://s3-external-1.amazonaws.com/pkgr-buildpack-ruby/20140408175240-ubuntu-14.04/ruby-2.1.0.tgz -s -o - | tar zxf -' failed unexpectedly:
 !     
 !     gzip: stdin: unexpected end of file
 !     tar: Child returned status 1
 !     tar: Error is not recoverable: exiting now
 !
 ! ERROR: compile failed
```

**Comment by vjm** [comment]
How do we know which buildpacks are supported by pkgr?

**Comment by crohr** [comment]
@vjm you can have a look into the data/builpacks folder. For instance https://github.com/crohr/pkgr/blob/master/data/buildpacks/debian-8. As for the supported ruby version, have a look at the documentation at https://packager.io/documentation/ruby/

**Comment by vjm** [comment]
Thanks @crohr!

I was able to get some other versions supported using this buildpack on Heroku by removing the stack reference: https://github.com/vjm/heroku-buildpack-ruby/commit/cdc905aaca3706c8d2e871b8f1d8884576d2bcfa
