### ISSUE TITLE
.git directory inside RPM

### ISSUE THREAD

**Issue by mitfik** [crohr/pkgr#44]
Hi, 

I would like to ask why a rpm package which is build by pkgr includes .git directory?
I checked in the code and I can see that there is just a cache. I do not see any value of having it inside the rpm package? Could you provide more information what for it is and if this can be removed?

Thanks a lot

**Comment by benlangfeld** [comment]
This was fixed in https://github.com/crohr/pkgr/commit/f297b43fc48b5a44b9b4db03457c54471c392533 and this ticket can be closed.

**Comment by crohr** [comment]
Thanks @benlangfeld. This was indeed fixed. Closing now.
