### ISSUE TITLE
run rake task without sudo

### ISSUE THREAD

**Issue by jpaas** [crohr/pkgr#53]
Is there any way that my app user can run a rake task without using sudo? It seems like there should be a way. 

BTW - pkgr is amazing. Works so well. Saved my ass.

**Comment by crohr** [comment]
Actually this is something I want to fix. [This](https://github.com/crohr/pkgr/blob/master/data/cli/cli.sh.erb#L44-L48) should be replaced with just checking whether the current user trying to execute the CLI has the right to read one of the files in /etc/your-app/conf.d (which would include the app user).

**Comment by crohr** [comment]
I've just pushed a change on the testing branch, which should allow what you want (https://github.com/crohr/pkgr/commit/34af6d3e2b815a298187536c4a0b3631afeb42f5). By any chance, could you test and let me know if it works for you?

**Comment by crohr** [comment]
Just pushed v1.4.3 with the change. All the commands can now be run with the APP_USER, except `scale`, `configure`, and `reconfigure`.

**Comment by jpaas** [comment]
Thanks @crohr. I'll give it a try tomorrow.
