### ISSUE TITLE
It should be possible to include installer wizards in the application's source

### ISSUE THREAD

**Issue by benlangfeld** [crohr/pkgr#54]
This makes keeping installer options inline with application capabilities easier. It seems it's currently only possible to specify a repository, and it even has to be on Github.

**Comment by benlangfeld** [comment]
A few questions to aid my attempt to contribute this, @crohr:

1. Why is addon installation duplicated between [`Builder`](https://github.com/crohr/pkgr/blob/master/lib/pkgr/builder.rb#L115-L124) and [`Installer`](https://github.com/crohr/pkgr/blob/master/lib/pkgr/installer.rb#L30-L38).
2. Why is the installation of addons in `Installer` duplicating part of [`Addon#install!`](https://github.com/crohr/pkgr/blob/master/lib/pkgr/addon.rb#L66-L69)?

**Comment by benlangfeld** [comment]
I think the answer to question 1 is that the code in `Builder` should be nuked. OpenProject no longer uses it: https://github.com/opf/openproject/commit/fe072de37a7d319477ce78b40d578ad4eec94947

**Comment by benlangfeld** [comment]
I'm prepping a PR which removes legacy addons. That will form the basis of my work on this feature.

**Comment by crohr** [comment]
Yes you can go ahead on removing the legacy addons. And allowing local addons would be nice as well, so I'm looking forward to your PR ;)

**Comment by benlangfeld** [comment]
Closing in favour of #58
