### ISSUE TITLE
Installer functionality should be documented

### ISSUE THREAD

**Issue by benlangfeld** [crohr/pkgr#55]
I found out about the installer functionality via OpenProject and I'm using it on [SIP Treadmill](github.com/att-innovate/SIPtreadmill) but it unfortunately has no documentation.

**Comment by crohr** [comment]
I know :( This is not as stable as I would like, but in the meantime I've pushed a README at https://github.com/pkgr/installer

Let me know if you have specific questions, I'll be happy to answer them.

**Comment by benlangfeld** [comment]
Awesome, thanks @crohr.

**Comment by crohr** [comment]
Closing this for now (!). I'm not sure there is enough demand for it to consider making it official.
