### ISSUE TITLE
Control bundle config through pkgr?

### ISSUE THREAD

**Issue by mdr** [crohr/pkgr#60]
I'm trying to package my Rails app that depends on nokogiri. Apparently Bundler needs special configuration to build on my Ubuntu 14.04 VM: 

bundle config build.nokogiri "--use-system-libraries --with-xml2-include=/usr/include/libxml2"

Can I control that through pkgr? Otherwise it fails:

$ pkgr package simple-merchant/
-----> Ruby app
-----> Compiling Ruby/Rails
-----> Using Ruby version: ruby-2.0.0
-----> Installing dependencies using 1.7.12
       Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j2 --deployment
       Fetching gem metadata from https://rubygems.org/.........
       Installing rake 10.4.2
       Installing i18n 0.7.0
       Installing json 1.8.2
       Installing minitest 5.5.1
       Installing thread_safe 0.3.5
       Installing tzinfo 1.2.2
       Installing activesupport 4.2.1
       Installing builder 3.2.2
       Installing erubis 2.7.0
       Installing mini_portile 0.6.2
       Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.
       /tmp/d20150427-20456-8lhcav/opt/simple-merchant/vendor/ruby-2.0.0/bin/ruby extconf.rb
       checking if the C compiler accepts ... yes
       Building nokogiri using system libraries.
       libxml2 version 2.6.21 or later is required!
       *** extconf.rb failed ***
       Could not create Makefile due to some reason, probably lack of necessary
       libraries and/or headers.  Check the mkmf.log file for more details.  You may
       need configuration options.

**Comment by luizsignorelli** [comment]
Hello,

I was able to do this using bundler's **--local** option. This option writes the config in the app directory so pkgr will have access to it.

Try this:
```
bundle config --local build.nokogiri "--use-system-libraries --with-xml2-include=/usr/include/libxml2"
```

**Comment by mdr** [comment]
Thanks, that works a treat!

**Comment by crohr** [comment]
Thanks for the tip @luizsignorelli !

**Comment by andyjeffries** [comment]
Was there any way of controlling this through .pkgr.yml?  The problem is that running that on my Debian build server doesn't make any difference - I get the same error.  And if I set it in the repository, it'll affect my OS X development machine.

**Comment by andyjeffries** [comment]
Even leaving out the `--local` when running the `bundle config` command on the build machine doesn't work (I don't know if anyone would expect it to).

**Comment by crohr** [comment]
@andyjeffries I suppose you could run that command as a before step in the `.pkgr.yml` file, so that it gets run on the build machine?

```yaml
before:
  - bundle config --local build.nokogiri "--use-system-libraries --with-xml2-include=/usr/include/libxml2"
```
