### ISSUE TITLE
master upstart conf needs to wait until filesystem is started

### ISSUE THREAD

**Issue by jpaas** [crohr/pkgr#63]
pkgr was working great for our app on one Ubuntu 12.04 machine and then we tried it on another and it refused to start our service on boot. We found that it was failing because although the network dependency had been satisfied, the filesystem was slower to come up and it was unable to write the log for our webserver.

Adding the filesystem dependency to our master conf file fixed it...

```
start on (started network-interface
          or started network-manager
          or started networking) and filesystem

# The `networking` job is a task, which means it will be stopped after the network interfaces have been configured.
# That's why we don't stop on "stopping networking".
# See <https://github.com/ddollar/foreman/issues/263>
stop on runlevel [!2345]
```

**Comment by crohr** [comment]
Fixed in https://github.com/crohr/pkgr/commit/38b2154af43ec2dc58529545a5a468195791b79f. Will be released in the next version. Thanks!
