### ISSUE TITLE
Build pipeline support

### ISSUE THREAD

**Issue by benlangfeld** [crohr/pkgr#73]
First, a regular reminder: pkgr and Packager.io are awesome!

We're delivering more and more of our software as packages using Packager.io, and one thing that is currently missing and preventing us from moving forward with other projects is integration into a CI pipeline. Ideally I would like to build and publish packages only for commits which passed CI.

It strikes me that perhaps Github's commit-marking API might be useful for this, such that Packager builds might only be triggered by a successful Travis CI build of a commit or similar workflow?

Additionally it would be nice for Packager to mark commits as built such that I could then monitor for that and use it to trigger deployments, or maybe even Packager could raise events of its own.

**Comment by crohr** [comment]
This is definitely something I want to implement on Packager.io. Using the Github Statuses API should indeed be sufficient for what we want to achieve.

Note that right now you could be notified of when a build terminates using the `after` hook in your `.pkgr.yml` file (using curl to post something to a third-party deployment process for instance).

**Comment by crohr** [comment]
packager.io is going to switch to GitHub Actions soon, at this point this will automatically be reflected.
