### ISSUE TITLE
DB authentication failed when running build

### ISSUE THREAD

**Issue by dsemenovsky** [crohr/pkgr#77]
I got following message after updating gem 'devise_token_auth' to version 0.1.32:
``` sh
PG::ConnectionBad: FATAL:  password authentication failed for user "user"
```
which executes method:

**Comment by crohr** [comment]
Looks like your app needs to connect to a postgres instance while building the app (I suppose while precompiling rails assets?). Either start a postgres instance on your build machine, or fix your rails code so that that kind of unnecessary connection does not happen.
