### ISSUE TITLE
Jessie/Debian 8 systemd not working

### ISSUE THREAD

**Issue by andyjeffries** [crohr/pkgr#79]
I don't know if it works for others, but it's not working for me with Debian 8.  My .pkgr.yml looks like this:

```
$ more .pkgr.yml 
targets:
  debian-7:
  debian-8:
  centos-7:
```

I added in centos-7 (in the hope it fixes the issue) and previously I just had debian-8, but now I'm trying anything to get it to add in support.

Trying to bring the web server up (Rails app) on a Jessie/Debian 8 box gives this:

```
$ sudo myapp scale web=1
[sudo] password for andy.jeffries: 
Scaling up...
cp: cannot stat ‘/opt/myapp/vendor/pkgr/scaling/systemd/myapp.service’: No such file or directory
```

Any ideas?  The scaling folder literally includes just this (no systemd folder at all):

```
$ tree /opt/myapp/vendor/pkgr/scaling
/opt/myapp/vendor/pkgr/scaling
└── upstart
    ├── myapp
    ├── myapp.conf
    ├── myapp-console.conf
    ├── myapp-console-PROCESS_NUM.conf
    ├── myapp-rake.conf
    ├── myapp-rake-PROCESS_NUM.conf
    ├── myapp-web.conf
    ├── myapp-web-PROCESS_NUM.conf
    ├── myapp-worker.conf
    └── myapp-worker-PROCESS_NUM.conf

1 directory, 10 files
```

**Comment by crohr** [comment]
Looks like the build machine incorrectly selects upstart init scripts instead of systemd. Could you run the `pkgr` command with `--force-os debian-8` and see what happens? Also, could you run `pkgr` in debug mode and send me the output where the distribution name as found by `pkgr` is displayed?

**Comment by andyjeffries** [comment]
Sorry, we wiped the server so it's no longer using Jessie because we were blocked.  The next time I try Jessie I'll re-open this ticket and let you know, but unless anyone else is hitting the same issue I guess it can be closed.
