### ISSUE TITLE
PORT problems again :(

### ISSUE THREAD

**Issue by seven1m** [crohr/pkgr#82]
Sorry, but I'm still struggling with PORT problems, though I did get past #81, which is great!

When I scale my web app to 2, here's what gets created for the second node:

```
cat /etc/systemd/system/onebody-web-2.service

[Unit]
StopWhenUnneeded=true
Requires=onebody-web.service
After=onebody-web.service

[Service]
Environment=PORT=3001
ExecStart=/usr/bin/onebody run web
Restart=always
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=%n

[Install]
WantedBy=onebody-web.service
```

The `PORT` is set in the environment as I expected, great!

However, when I start the service, this second node thinks the PORT is set to 3000. 😣

```
sudo systemctl status onebody-web-2

● onebody-web-2.service
   Loaded: loaded (/etc/systemd/system/onebody-web-2.service; enabled)
   Active: active (running) since Thu 2015-09-24 22:37:29 CDT; 293ms ago
 Main PID: 11433 (ruby)
   CGroup: /system.slice/onebody-web-2.service
           └─11433 ruby /opt/onebody/vendor/bundle/ruby/2.2.0/bin/thin start -p 3000
```

I've tracked the problem down (I think) to line 300 of the binary generated by pkgr, which reads:

```
exec chroot --userspec ${APP_USER}:${APP_GROUP} "/" sh -c "cd $(_p ${APP_HOME}) && $runnable"
```

This line doesn't seem to transfer the environment over? I'm a bash n00b, so I don't really know how to fix this.

But I did verify the PORT is read properly if I change this line to read:

```
exec chroot --userspec ${APP_USER}:${APP_GROUP} "/" sh -c "cd $(_p ${APP_HOME}) && PORT=3001 $runnable"
```

(I know that's lame, but just wanted to confirm where the environment isn't getting transferred over.)

Any thoughts on how to fix?

**Comment by seven1m** [comment]
OK, some more debugging, and I'm way off of course. 😜

If I `echo $PORT >> /tmp/port.txt` from within the pkgr-generated `/usr/bin/onebody` binary, it writes 3000 to the file for both processes. So PORT isn't getting set by this time either. So maybe it's a problem with how the systemd service file is set up??

At least I have some more stuff to google now. 😀

**Comment by seven1m** [comment]
I think I found it!

In the binary, the `/etc/onebody/conf.d/other` file is read, and it contains `export PORT=3000` because that's what I set it to when I ran `onebody config:set PORT=3000`.

https://github.com/crohr/pkgr/blob/master/data/cli/cli.sh.erb#L51-L55

```ruby
for file in $(_p "/etc/${APP_NAME}/conf.d")/*; do
  if [ -f $file ]; then . $file; fi
done
```

**Comment by seven1m** [comment]
Here is a patch that "fixes" the issue:

```patch
diff --git a/data/cli/cli.sh.erb b/data/cli/cli.sh.erb
index a6d213a..e39adea 100644
--- a/data/cli/cli.sh.erb
+++ b/data/cli/cli.sh.erb
@@ -50,6 +50,7 @@ fi

 # Source all environment variables for the app. This must be done as
 # privileged user since the config variables are only readable by root.
+PORT_WAS=$PORT
 for file in $(_p "/etc/${APP_NAME}/conf.d")/*; do
   if [ -f $file ]; then . $file; fi
 done
@@ -293,6 +294,9 @@ while : ; do
         runnable="${runnable}$(printf " %q" ${COMMAND} "$@")"
       fi

+      # fix port
+      export PORT=$PORT_WAS
+
       # Do not use su, to avoid creating a new process. Note: chroot version
       # is too old on Ubuntu Lucid, so this will fail. It works on Debian
       # Squeeze though (and later).
```

I'm sure this isn't the right way to fix this issue, though. If you care to direct me, I'll be happy to make a PR.

**Comment by crohr** [comment]
@seven1m you're right, environment variables declared in `/etc/app/conf.d/*` will overwrite anything set in the init scripts. Since `PORT` is the only variable that needs special treatment, maybe something similar to your fix could be used. I'll think about it.
