### ISSUE TITLE
Remove default dependencies

### ISSUE THREAD

**Issue by bpaquet** [crohr/pkgr#84]
Is there any way to remove default dependencies ? They are not needed for my project, and I do not want to install them in production :)

mysql-common, libpq5, libxml2, libxslt1.1, libreadline5, libreadline6

**Comment by Trozz** [comment]
+1

**Comment by crohr** [comment]
Just added a `default_dependencies: false` option for your `.pkgr.yml` file. This change is in the master branch, let me know if it works for you.

**Comment by bpaquet** [comment]
Thx !

Can we use it from pkgr.io ?

**Comment by crohr** [comment]
@bpaquet yes, Packager.io is now up to date with the latest version.

**Comment by lukaszkorecki** [comment]
Is there a command line option for this?

**Comment by crohr** [comment]
@lukaszkorecki not yet. I'm not sure I want to make every command accessible via the CLI though. Is it a no-go for you to add a `.pkgr.yml` file?

**Comment by lukaszkorecki** [comment]
@crohr my assumption was that if I set `--dependencies` flag to nothing it will do the same thing as the setting in .pkgr.yml

Using config files is definitely an option, I just feel that if something's configurable I'd expect to find a corresponding command-line flag
