### ISSUE TITLE
Provide a way to restart without using distro specific command

### ISSUE THREAD

**Issue by bpaquet** [crohr/pkgr#86]
From postinst, I have to restart. The only current way without using distro specific command is

```
my_prod scale main=0 || true
my_prod scale main=1 || true
```

Something like

```
my_prod restart_all
```

**Comment by crohr** [comment]
`service my-app restart` works on a lot of systems, but yes adding start/stop/restart commands to the CLI is on the todo list.

**Comment by Veske** [comment]
service my-app restart says it does what it should but if I tell it to stop, then the app is actually still available.

**Comment by crohr** [comment]
A `my-app restart` command is available in the `master` branch. You can restrict to specific process types with `my-app restart web` for instance.
