### ISSUE TITLE
Buildpack path replacement is troublesome

### ISSUE THREAD

**Issue by benlangfeld** [crohr/pkgr#92]
pkgr [replaces instances of the string `/app` in buildpacks](https://github.com/crohr/pkgr/blob/master/lib/pkgr/buildpack.rb#L101) with the path to the application post-install, which is typically `/opt/${NAME}`, per https://github.com/crohr/pkgr/issues/37#issuecomment-127338867.

The Elixir buildpack includes the string `/app` [where it should not be replaced](https://github.com/HashNuke/heroku-buildpack-elixir/blob/master/bin/compile#L23). Unfortunately, pkgr doesn't know any better, replaces it, and thus breaks the buildpack.

**Comment by crohr** [comment]
It would probably be better to replace `/app/` instead of `/app`. I'll have to check whether that breaks the officially supported buildpacks or not.
