### ISSUE TITLE
pkgr is incompatible with buildpacks which require the app home directory be available at compile time

### ISSUE THREAD

**Issue by benlangfeld** [crohr/pkgr#93]
For example https://github.com/HashNuke/heroku-buildpack-elixir:

```
-----> Checking Erlang and Elixir versions
       WARNING: elixir_buildpack.config wasn't found in the app
       Using default config from Elixir buildpack
       Will use the following versions:
       * Stack
       * Erlang 18.1.3
       * Elixir 1.2.0
       Will export the following config vars:
       * Config vars DATABASE_URL
       * MIX_ENV=prod
-----> Stack changed, will rebuild
-----> Fetching Erlang 18.1.3
-----> Installing Erlang 18.1.3 (changed)
mkdir: cannot create directory '/opt/vagrant': Permission denied
ln: failed to create symbolic link '/opt/vagrant/.platform_tools/erlang': No such file or directory
Install: need <ERL_ROOT> directory as argument
Usage: Install [-cross] [-minimal|-sasl] <ERL_ROOT>
```

It appears that this may also be the case for [the Python buildpack](https://github.com/crohr/pkgr/issues/37#issuecomment-125251848).

**Comment by benlangfeld** [comment]
I think that ideally we want to prefix the installation path (`/opt/vagrant` in this case) with the build directory (`/tmp/something`) when it is used at compile time, but we cannot easily distinguish instances of the installation path in a buildpack between compile time (this example) and runtime usage (which appears to [come from the PHP buildpack including configuration templates](https://github.com/crohr/pkgr/commit/022095fa2df85a44ef66131affee35f6ff0c3b4b)).

**Comment by crohr** [comment]
@benlangfeld The Go buildpack has the same issue (https://github.com/heroku/heroku-buildpack-go/blob/master/bin/compile#L205). I just pushed a fix, although this does not fix the issue for precompiled binaries that assume they'll be installed in `/app`, and fail to start at runtime (is it what your second paragraph was about? I'm not sure I understand what you wanted to say).

I'm actually building a separate service to address the issue of compiling binaries for the right install prefix (https://github.com/crohr/buildcurl), and hopefully I can soon include those in the buildpacks used by Packager.io, the idea being to replace `curl` calls that download stuff from the buildpack's S3 bucket with a buildcurl call. E.g. for ruby (even though the install prefix is not a show-stopper here):

```
curl https://s3.amazonaws.com/heroku-buildpack-ruby/ruby-2.3.0.tgz -o - | tar xzf ...
```

becomes

```
curl http://buildcurl.com -d recipe=ruby -d target=ubuntu:14.04 -d version=2.3.0 -d prefix=/opt/app-name -o - | tar xzf ...
```

**Comment by crohr** [comment]
I'm closing this since the original issue is fixed (but we can continue the discussion wrt runtime deps).
