### ISSUE TITLE
Disable default build dependencies

### ISSUE THREAD

**Issue by jacob-carlborg** [crohr/pkgr#97]
There doesn't seem to be a way to disable or configure the default build dependencies. If I specify `build_dependencies:` it installs the default ones anyway. For example, I don't see a reason to install all database libraries when I only need one of them. When building it actually only reports a warning but it's still annoying.

**Comment by crohr** [comment]
Note that this is now supported (https://packager.io/documentation/customizing-the-build/#default_dependencies)

```yaml
default_dependencies: false
```

**Comment by jacob-carlborg** [comment]
Can we expect a new release soon? I would expect there to already be a new release if that documentation is updated.
