### ISSUE TITLE
CentOS 6 upstart

### ISSUE THREAD

**Issue by diegossilveira** [crohr/pkgr#99]
When building packages for CentOS 6, **pkgr** generates upstart scripts by default. These scripts looks like this:

```
start on (started network-interface
          or started network-manager
          or started networking)
```

Those services (*network-interface*, *network-manager* and *networking*) may not exist on CentOS 6.7 (as far as I know), and consequently, service won't start automatically on boot time.

**Comment by crohr** [comment]
This is no longer the case, it now starts on specific runlevels. Closing.
